### ISSUE TITLE
標準入力から変換できるようにしたい

### ISSUE THREAD

**Issue by 515hikaru** [37108/md2bg#76]
使わせてもらっています、ありがとうございます。

現状、ファイルのみ対応しているようですが、標準入力を受け付けるように機能拡張をするのはいかがでしょうか、という提案です。

例えば、 Mac ならばテキストエディタのバッファなどに書いた Markdown の内容をクリップボードにコピーして、

```
pbpaste | md2bg
```

というコマンドで変換できると便利だと思っています。

わたしは Markdown 文書を、ファイルを直接編集しないエディタ（Boostnote のような）で書くことが多いので、今の仕様だと一度 Markdown 文書をコピペしてファイルを作ってから、 `md2bg` で変換する必要があり、ちょっと手間です。

もし同意いただけるなら PR 作ろうかと思っていますが、どうでしょうか。

**Comment by 37108** [comment]
@515hikaru 
Issue起票ありがとうございます。

> 現状、ファイルのみ対応しているようですが、標準入力を受け付けるように機能拡張をするのはいかがでしょうか、という提案です。

より便利になりそうで是非とも取り入れたい機能です。PRの作成よろしくお願いします。

**Comment by 515hikaru** [comment]
@37108 ありがとうございます！近日中に取り掛かりますね。

大雑把に2つ方針があり、どちらが良いと思いますか？

### オプションを追加する

```sh
# 引数を渡さない場合今と同じ挙動
$ echo "foo" | md2bg
need file path args
npx md2bg <file path>
# オプションを渡すことで標準入力から読み込む
$ echo "foo" | md2bg --stdin
foo
$ md2bg --stdin
# ここで標準入力の入力待ち状態になる
foo
^D
foo
```

- Pros) オプションを使わない挙動は今までと変わらない
- Cons) option parser が必要になる

### 引数がない場合暗黙に標準入力を受け取る

```sh
＄echo "foo" | md2bg
foo
$ md2bg
# ここで標準入力の入力待ち状態になる
foo
^D
foo
$ md2bg input.md
# 既存の動作
```

- `cat` コマンドみたいな感じ
- Pros) 追加でパッケージを導入する必要はない
- Cons) 暗黙的に標準入力を使う挙動がわかりづらいと感じる(少なくともわたしは)

**Comment by 37108** [comment]
@515hikaru 

ご提案ありがとうございます。

一番は 515hikaru さんが違和感なくこの機能を使えることがベストだと思っているので前者の方向で検討していただいてもよろしいでしょうか。

また後者で実装した場合には、引数がない場合にエラーを返せないので別途`--help`のようなオプションが必要になると考えています（前者、後者かかわらずに、ここの実装有無については別途検討が必要ですが）。
ですのでいずれにしてもoption parserは今後必要になると思います。
